/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WebApp;

import static spark.Spark.get;
import static spark.Spark.port;
import static spark.Spark.post;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;



import spark.ModelAndView;
import spark.template.mustache.MustacheTemplateEngine;

public class App {
    
    
    public String getGreeting() {
        return "Hello world.";
    }

    public static Integer Hesapla(ArrayList<Integer> array, int yas, int gunlukSigara, int haftalikSpor){


    


        if(array == null){
            System.out.println("Dizi Boş");
        }
        int ortalamaYasamSuresi = 70;
        //yas hesaplama formulu
        int sonuc = yas - gunlukSigara / 3 + (haftalikSpor * 3);
        array.add(yas);
        array.add(gunlukSigara);
        array.add(haftalikSpor);
        
        return ortalamaYasamSuresi - sonuc;

        
    }

    public static void main(String[] args) {
        port(getHerokuAssignedPort());
        get("/", (req, res) -> "Merhaba Dünya");
        post("/compute", (req, res) -> {
            // System.out.println(req.queryParams("input1"));
            // System.out.println(req.queryParams("input2"));
            int yasInput = Integer.parseInt(req.queryParams("input1")) ;
            int sigaraInput = Integer.parseInt(req.queryParams("input2")) ;
            int sporInput = Integer.parseInt(req.queryParams("input3")) ;
           
           
            java.util.ArrayList<Integer> inputList = new java.util.ArrayList<>();
            
                inputList.add(yasInput);
                inputList.add(sigaraInput);
                inputList.add(sporInput);
            
            // while (sc1.hasNext()) {
            //     int value = Integer.parseInt(sc1.next().replaceAll("\\s", ""));
            //     inputList.add(value);
            // }
            
            //sc1.close();
            System.out.println(inputList);
            //String input2 = req.queryParams("input2").replaceAll("\\s", "");
            //int input2AsInt = Integer.parseInt(input2);
            int yas = inputList.get(0);
            int sigara = inputList.get(1);
            int spor = inputList.get(2);
            int result = App.Hesapla(inputList, yasInput, sigaraInput, sporInput);
            
            
            Map<String, Integer> map = new HashMap<String, Integer>();
            map.put("result", result );
            map.put("yas", yas );
            map.put("sigara", sigara );
            map.put("spor", spor );
            return new ModelAndView(map, "compute.mustache");
        }, new MustacheTemplateEngine());
        get("/compute",
                (rq, rs) -> {
                    Map<String, String> map = new HashMap<String, String>();
                    map.put("result", "Deger Girilmedi");
                    return new ModelAndView(map, "compute.mustache");
                },
                new MustacheTemplateEngine());
    }

    static int getHerokuAssignedPort() {
        ProcessBuilder processBuilder = new ProcessBuilder();
        if (processBuilder.environment().get("PORT") != null) {
            return Integer.parseInt(processBuilder.environment().get("PORT"));
        }
        return 4567; // return default port if heroku-port isn't set (i.e. on localhost)
    }
}
